import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;

public class Insert_Into_Database {
	public static void main(String args[]){
		Map<String,Double> map_rates=new HashMap<String,Double>();
		map_rates=new HashMap<String,Double>();
		map_rates.put("Asparagus", 20.00);
		map_rates.put("Broccoli", 25.00);
		map_rates.put("Carrots", 46.00);
		map_rates.put("Cauliflower", 30.00);
		map_rates.put("Celery", 24.00);
		map_rates.put("Corn", 18.00);
		map_rates.put("Cucumbers", 23.00);
		map_rates.put("Lettuce / Greens", 26.00);
		map_rates.put("Onions", 40.00);
		map_rates.put("Peppers", 35.00);
		map_rates.put("Potatoes", 40.00);
		map_rates.put("Squash", 45.00);
		map_rates.put("Zucchini", 55.00);
		map_rates.put("Tomatoes", 42.00);
		map_rates.put("Brinjal", 43.00);
		map_rates.put("Beetroot", 45.00);
		map_rates.put("Beans", 40.00);
		map_rates.put("Apples", 15.00);
		map_rates.put("Bananas", 25.00);
		map_rates.put("Berries", 17.00);
		map_rates.put("Cherries", 22.00);
		map_rates.put("Grapefruit", 15.00);
		map_rates.put("Grapes", 35.00);
		map_rates.put("Lemons", 36.00);
		map_rates.put("Melon", 50.00);
		map_rates.put("Oranges", 37.00);
		map_rates.put("Papaya", 25.00);
		map_rates.put("Nectarines", 20.00);
		map_rates.put("Pears", 33.00);
		map_rates.put("Strawberries", 64.00);
		map_rates.put("Mango", 18.00);
		map_rates.put("Bagels", 25.00);
		map_rates.put("Chip dip", 30.00);
		map_rates.put("English muffins", 25.00);
		map_rates.put("Eggs / Fake eggs", 55.00);
		map_rates.put("Fruit juice", 20.00);
		map_rates.put("Ready-bake breads", 25.00);
		map_rates.put("Tofu", 23.00);
		map_rates.put("Tortillas", 27.00);
		map_rates.put("Breakfasts", 26.00);
		map_rates.put("Burritos", 28.00);
		map_rates.put("Fish sticks", 26.00);
		map_rates.put("Ice cream / Sorbet", 40.00);
		map_rates.put("Juice concentrate", 30.00);
		map_rates.put("Pizza / Pizza Rolls", 110.00);
		map_rates.put("Popsicles", 25.00);
		map_rates.put("Fries / Tater tots", 99.00);
		map_rates.put("Vegetables", 80.00);
		map_rates.put("TV dinners", 35.00);
		map_rates.put("Veggie burgers", 99.00);
		map_rates.put("BBQ sauce", 89.00);
		map_rates.put("Gravy", 69.00);
		map_rates.put("Honey", 49.00);
		map_rates.put("Hot sauce", 59.00);
		map_rates.put("Jam / Jelly / Preserves", 39.00);
		map_rates.put("Ketchup / Mustard", 59.00);
		map_rates.put("Mayonnaise", 39.00);
		map_rates.put("Pasta sauce", 53.00);
		map_rates.put("Relish", 24.00);
		map_rates.put("Salad dressing", 85.00);
		map_rates.put("Salsa", 42.00);
		map_rates.put("Soy sauce", 42.00);
		map_rates.put("Steak sauce", 35.00);
		map_rates.put("Syrup", 50.00);
		map_rates.put("Worcestershire sauce", 39.00);
		map_rates.put("Bouillon cubes", 185.00);
		map_rates.put("Cereal", 122.00);
		map_rates.put("Coffee / Filters", 89.00);
		map_rates.put("Instant potatoes", 99.00);
		map_rates.put("Lemon / Lime juice", 79.00);
		map_rates.put("Mac & cheese", 78.00);
		map_rates.put("Olive oil", 74.00);
		map_rates.put("Pancake / Waffle mix", 125.00);
		map_rates.put("Pasta", 120.00);
		map_rates.put("Peanut butter", 99.00);
		map_rates.put("Pickles", 119.00);
		map_rates.put("Rice", 85.00);
		map_rates.put("Tea", 110.00);
		map_rates.put("Vegetable oil", 111.00);
		map_rates.put("Vinegar", 59.00);
		map_rates.put("Applesauce", 100.00);
		map_rates.put("Baked beans", 111.00);
		map_rates.put("Chili", 60.00);
		map_rates.put("Fruit", 89.00);
		map_rates.put("Tinned meats", 122.00);
		map_rates.put("Tuna / Chicken", 160.00);
		map_rates.put("Soups", 145.00);
		map_rates.put("Tomatoes", 89.00);
		map_rates.put("Veggies", 112.00);
		map_rates.put("Basil", 99.00);
		map_rates.put("Black pepper", 72.00);
		map_rates.put("Cilantro", 79.00);
		map_rates.put("Cinnamon", 89.00);
		map_rates.put("Garlic", 69.00);
		map_rates.put("Ginger", 110.00);
		map_rates.put("Mint", 111.00);
		map_rates.put("Oregano", 99.00);
		map_rates.put("Paprika", 98.00);
		map_rates.put("Parsley", 96.00);
		map_rates.put("Red pepper", 154.00);
		map_rates.put("Salt", 33.00);
		map_rates.put("Spice mix", 120.00);
		map_rates.put("Vanilla extract", 100.00);
		map_rates.put("Butter / Margarine", 133.00);
		map_rates.put("Cottage cheese", 113.00);
		map_rates.put("Half & half", 137.00);
		map_rates.put("Milk", 25.00);
		map_rates.put("Olives", 55.00);
		map_rates.put("Sour cream", 35.00);
		map_rates.put("Whipped cream", 45.00);
		map_rates.put("Bleu cheese", 89.00);
		map_rates.put("Cheddar", 88.00);
		map_rates.put("Cottage cheese", 87.00);
		map_rates.put("Cream cheese", 86.00);
		map_rates.put("Feta", 85.00);
		map_rates.put("Goat cheese", 85.00);
		map_rates.put("Mozzarella / Provolone", 86.00);
		map_rates.put("Parmesan", 84.00);
		map_rates.put("Ricotta", 85.00);
		map_rates.put("Provolone", 83.00);
		map_rates.put("Sandwich slices", 81.00);
		map_rates.put("Swiss", 82.00);
		map_rates.put("Bacon / Sausage", 133.00);
		map_rates.put("Beef", 154.00);
		map_rates.put("Chicken", 160.00);
		map_rates.put("Ground beef / Turkey", 170.00);
		map_rates.put("Ham / Pork", 200.00);
		map_rates.put("Hot dogs", 225.00);
		map_rates.put("Lunchmeat", 230.00);
		map_rates.put("Turkey", 233.00);
		map_rates.put("Catfish", 208.00);
		map_rates.put("Crab", 133.00);
		map_rates.put("Lobster", 108.00);
		map_rates.put("Mussels", 135.00);
		map_rates.put("Oysters", 175.00);
		map_rates.put("Salmon", 173.00);
		map_rates.put("Shrimp", 180.00);
		map_rates.put("Tilapia", 160.00);
		map_rates.put("Tuna", 164.00);
		map_rates.put("Beer", 80.00);
		map_rates.put("Club soda / Tonic", 25.00);
		map_rates.put("Champagne", 99.00);
		map_rates.put("Gin", 85.00);
		map_rates.put("Juice", 84.00);
		map_rates.put("Mixers", 83.00);
		map_rates.put("Red wine / White wine", 81.00);
		map_rates.put("Rum", 79.00);
		map_rates.put("Saké", 77.00);
		map_rates.put("Soda pop", 78.00);
		map_rates.put("Sports drink", 25.00);
		map_rates.put("Whiskey", 185.00);
		map_rates.put("Vodka", 375.00);
		map_rates.put("Bagels / Croissants", 82.00);
		map_rates.put("Buns / Rolls", 45.00);
		map_rates.put("Cake / Cookies", 120.00);
		map_rates.put("Donuts / Pastries", 80.00);
		map_rates.put("Fresh bread", 25.00);
		map_rates.put("Sliced bread", 52.00);
		map_rates.put("Pie! Pie! Pie!", 53.00);
		map_rates.put("Pita bread", 33.00);
		map_rates.put("Baking powder / Soda", 33.00);
		map_rates.put("Bread crumbs", 34.00);
		map_rates.put("Cake / Brownie mix", 39.00);
		map_rates.put("Cake icing / Decorations", 36.00);
		map_rates.put("Chocolate chips / Cocoa", 33.00);
		map_rates.put("Flour", 33.00);
		map_rates.put("Shortening", 33.00);
		map_rates.put("Sugar", 40.00);
		map_rates.put("Sugar substitute", 101.00);
		map_rates.put("Candy / Gum", 15.00);
		map_rates.put("Cookies", 35.00);
		map_rates.put("Crackers", 130.00);
		map_rates.put("Dried fruit", 33.00);
		map_rates.put("Granola bars / Mix", 29.00);
		map_rates.put("Nuts / Seeds", 25.00);
		map_rates.put("Oatmeal", 38.00);
		map_rates.put("Popcorn", 40.00);
		map_rates.put("Potato / Corn chips", 30.00);
		map_rates.put("Pretzels", 197.00);
		map_rates.put("Burger night", 225.00);
		map_rates.put("Chili night", 198.00);
		map_rates.put("Pizza night", 199.00);
		map_rates.put("Spaghetti night", 158.00);
		map_rates.put("Taco nigh", 152.00);
		map_rates.put("Take-out deli food", 103.00);
		map_rates.put("Baby food", 110.00);
		map_rates.put("Diapers", 85.00);
		map_rates.put("Formula", 83.00);
		map_rates.put("Lotion", 82.00);
		map_rates.put("Baby wash", 36.00);
		map_rates.put("Wipes", 92.00);
		map_rates.put("Cat food / Treats", 97.00);
		map_rates.put("Cat litter", 103.00);
		map_rates.put("Dog food / Treats", 133.00);
		map_rates.put("Flea treatment", 15.00);
		map_rates.put("Pet shampoo", 100.00);
		map_rates.put("Antiperspirant / Deodorant", 118.00);
		map_rates.put("Bath soap / Hand soap", 40.00);
		map_rates.put("Condoms / Other b.c.", 234.00);
		map_rates.put("Cosmetics", 28.00);
		map_rates.put("Cotton swabs / Balls", 22.00);
		map_rates.put("Facial cleanser", 19.00);
		map_rates.put("Facial tissue", 13.00);
		map_rates.put("Feminine products", 35.00);
		map_rates.put("Floss", 26.00);
		map_rates.put("Hair gel / Spray", 39.00);
		map_rates.put("Lip balm", 45.00);
		map_rates.put("Moisturizing lotion", 51.00);
		map_rates.put("Mouthwash", 30.00);
		map_rates.put("Razors / Shaving cream", 32.00);
		map_rates.put("Shampoo / Conditioner", 39.00);
		map_rates.put("Sunblock", 33.00);
		map_rates.put("Toilet paper", 33.00);
		map_rates.put("Toothpaste", 38.00);
		map_rates.put("Vitamins / Supplements", 50.00);
		map_rates.put("Allergy", 18.00);
		map_rates.put("Antibiotic", 15.00);
		map_rates.put("Antidiarrheal", 13.00);
		map_rates.put("Aspirin", 10.00);
		map_rates.put("Antacid", 45.00);
		map_rates.put("Band-aids / Medical", 28.00);
		map_rates.put("Cold / Flu / Sinus", 36.00);
		map_rates.put("Pain reliever", 34.00);
		map_rates.put("Prescription pick-up", 33.00);
		map_rates.put("Aluminum foil", 35.00);
		map_rates.put("Napkins", 41.00);
		map_rates.put("Non-stick spray", 56.00);
		map_rates.put("Paper towels", 32.00);
		map_rates.put("Plastic wrap", 36.00);
		map_rates.put("Sandwich / Freezer bags", 33.00);
		map_rates.put("Wax paper", 32.00);
		map_rates.put("Air freshener", 35.00);
		map_rates.put("Bathroom cleaner", 35.00);
		map_rates.put("Bleach / Detergent", 33.00);
		map_rates.put("Dish / Dishwasher soap", 18.00);
		map_rates.put("Garbage bags", 30.00);
		map_rates.put("Glass cleaner", 30.00);
		map_rates.put("Mop head / Vacuum bags", 15.00);
		map_rates.put("Sponges / Scrubbers", 16.00);
		map_rates.put("CDRs / DVDRs", 15.00);
		map_rates.put("Notepad / Envelopes", 8.00);
		map_rates.put("Printer paper", 8.00);
		map_rates.put("Glue / Tape", 10.00);
		map_rates.put("Pens / Pencils", 5.00);
		map_rates.put("Postage stamps", 3.00);
		map_rates.put("Automotive", 33.00);
		map_rates.put("Batteries", 20.00);
		map_rates.put("Charcoal / Propane", 37.00);
		map_rates.put("Flowers / Greeting card", 40.00);
		map_rates.put("Insect repellent", 50.00);
		map_rates.put("Light bulbs", 35.00);
		map_rates.put("Newspaper / Magazine", 15.00);
		map_rates.put("Random impulse buy", 51.00);
		map_rates.put("Arsenic", 59.00);
		map_rates.put("Cigarettes", 50.00);
		map_rates.put("Asbestos", 101.00);
		map_rates.put("Radionuclides", 100.00);
		map_rates.put("Vinyl chloride", 183.00);
		map_rates.put("Hummus", 57.00);
		Connection c=null;
		Statement smt=null;
		try{
			Class.forName("org.sqlite.JDBC");
			c=DriverManager.getConnection("jdbc:sqlite:bill.db");
			System.out.println("Opened database successfully");
			smt=c.createStatement();
			ResultSet rs=null;

				String sql="select * from ITEMS;";
				rs=smt.executeQuery(sql);
				int count=0;
				while(rs.next()){
					count++;
					//String name=rs.getString("item_name");
					System.out.format("%-10s %-25s   %.2f",rs.getString(1),rs.getString(2),rs.getDouble(3));
					System.out.println();
				}
			smt.close();
			c.close();
			
		}catch (Exception e){
			System.err.println(e.getClass().getName()+": "+e.getMessage());
			System.exit(0);
		}
	}

}
