import java.util.HashMap;
import java.util.Map;

public class Item_Codes {
	private Map<String,String> code=new HashMap<String,String>();
	public Item_Codes(){
		code.put("Asparagus", "asp001");
		code.put("Broccoli", "bro002");
		code.put("Carrots", "car003");
		code.put("Cauliflower", "cau004");
		code.put("Celery", "cel005");
		code.put("Corn", "cor006");
		code.put("Cucumbers", "cuc007");
		code.put("Lettuce / Greens", "lgr008");
		code.put("Onions", "oni009");
		code.put("Peppers", "pep010");
		code.put("Potatoes", "pot011");
		code.put("Squash", "squ012");
		code.put("Zucchini", "zuc013");
		code.put("Tomatoes", "tom014");
		code.put("Brinjal", "bri015");
		code.put("Beetroot", "bee016");
		code.put("Beans", "bez017");
		code.put("Apples", "zpp018");
		code.put("Bananas", "bzn019");
		code.put("Berries", "ber020");
		code.put("Cherries", "che021");
		code.put("Grapefruit", "gra022");
		code.put("Grapes", "gra023");
		code.put("Lemons", "lem024");
		code.put("Melon", "mel025");
		code.put("Oranges", "ora026");
		code.put("Papaya", "pap027");
		code.put("Nectarines", "nect028");
		code.put("Pears", "pea029");
		code.put("Mango", "man030");
		code.put("Bagels", "bag031");
		code.put("Chip dip", "cdi032");
		code.put("English muffins", "emu033");
		code.put("Eggs / Fake eggs", "efg034");
		code.put("Fruit juice", "fju035");
		code.put("Ready-bake breads", "rbb036");
		code.put("Tofu", "tof037");
		code.put("Tortillas", "tor038");
		code.put("Breakfasts", "brf039");
		code.put("Burritos", "bur040");
		code.put("Fish sticks", "fis041");
		code.put("Ice cream / Sorbet", "ics042");
		code.put("Juice concentrate", "juc043");
		code.put("Pizza / Pizza Rolls", "ppr044");
		code.put("Fries / Tater tots", "ftt045");
		code.put("Vegetables", "veg046");
		code.put("TV dinners", "tvd047");
		code.put("Veggie burgers", "veb048");
		code.put("BBQ sauce", "bbg049");
		code.put("Gravy", "gra050");
		code.put("Honey", "hon051");
		code.put("Hot sauce", "hos052");
		code.put("Jam / Jelly / Preserves", "jjp053");
		code.put("Ketchup / Mustard", "kem054");
		code.put("Pasta sauce", "pas055");
		code.put("Mayonnaise", "may056");
		code.put("Relish", "rel057");
		code.put("Salad dressing", "sad058");
		code.put("Salsa", "sal059");
		code.put("Soy sauce", "sos060");
		code.put("Steak sauce", "sts061");
		code.put("Syrup", "syr062");
		code.put("Worcestershire sauce", "wos063");
		code.put("Bouillon cubes", "boc064");
		code.put("Cereal", "cer065");
		code.put("Coffee / Filters", "cof066");
		code.put("Instant potatoes", "ipo067");
		code.put("Lemon / Lime juice", "llj068");
		code.put("Mac & cheese", "mnc069");
		code.put("Olive oil", "ool070");
		code.put("Pancake / Waffle mix", "pwm071");
		code.put("Pasta", "pas072");
		code.put("Peanut butter", "peb073");
		code.put("Pickles", "pic074");
		code.put("Rice", "ric075");
		code.put("Tea", "tea078");
		code.put("Vegetable oil", "voi079");
		code.put("Vinegar", "vin080");
		code.put("Applesauce", "asa081");
		code.put("Baked beans", "bbe082");
		code.put("Chili", "chi083");
		code.put("Fruit", "fru083");
		code.put("Tinned meats", "tim084");
		code.put("Tuna / Chicken", "tuc085");
		code.put("Soups", "sou086");
		code.put("Tomatoes", "tom087");
		code.put("Veggies", "veg088");
		code.put("Basil", "bas89");
		code.put("Black pepper", "bpe090");
		code.put("Cilantro", "cil091");
		code.put("Cinnamon", "cin092");
		code.put("Garlic", "gar093");
		code.put("Ginger", "gin094");
		code.put("Mint", "min095");
		code.put("Oregano", "ore096");
		code.put("Paprika", "pap097");
		code.put("Parsley", "par098");
		code.put("Red pepper", "rpe099");
		code.put("Salt", "sal100");
		code.put("Spice mix", "sam101");
		code.put("Vanilla extract", "vae102");
		code.put("Butter / Margarine", "bma103");
		code.put("Cottage cheese", "che104");
		code.put("Half & half", "hnh105");
		code.put("Milk", "mil106");
		code.put("Olives", "oli107");
		code.put("Sour cream", "scr108");
		code.put("Whipped cream", "whc109");
		code.put("Bleu cheese", "bch110");
		code.put("Cheddar", "che111");
		code.put("Cottage cheese", "cch112");
		code.put("Cream cheese", "crc113");
		code.put("Feta", "fet114");
		code.put("Goat cheese", "goc115");
		code.put("Mozzarella / Provolone", "mop116");
		code.put("Parmesan", "par117");
		code.put("Ricotta", "ric118");
		code.put("Provolone", "pro119");
		code.put("Sandwich slices", "sans120");
		code.put("Swiss", "swi121");
		code.put("Bacon / Sausage", "bas122");
		code.put("Beef", "bee123");
		code.put("Chicken", "chi124");
		code.put("Ground beef / Turkey", "gbt125");
		code.put("Ham / Pork", "hap126");
		code.put("Hot dogs", "hod127");
		code.put("Lunchmeat", "lun128");
		code.put("Catfish", "caf129");
		code.put("Turkey", "tur129");
		code.put("Crab", "cra130");
		code.put("Lobster", "lob131");
		code.put("Mussels", "mus132");
		code.put("Oysters", "oys133");
		code.put("Salmon", "sal134");
		code.put("Shrimp", "shr135");
		code.put("Tilapia", "til136");
		code.put("Tuna", "tun137");
		code.put("Beer", "bee138");
		code.put("Club soda / Tonic", "cst139");
		code.put("Champagne", "cham140");
		code.put("Gin", "gin141");
		code.put("Juice", "jui142");
		code.put("Mixers", "mix143");
		code.put("Red wine / White wine", "rww144");
		code.put("Rum", "rum145");
		code.put("Saké", "sak146");
		code.put("Soda pop", "sop147");
		code.put("Sports drink", "spd148");
		code.put("Whiskey", "whi149");
		code.put("Vodka", "vod150");
		code.put("Bagels / Croissants", "bac151");
		code.put("Buns / Rolls", "bur152");
		code.put("Cake / Cookies", "cac153");
		code.put("Donuts / Pastries", "dop154");
		code.put("Fresh bread", "frb155");
		code.put("Sliced bread", "slb156");
		code.put("Pie! Pie! Pie!", "ppp157");
		code.put("Pita bread", "pi158");
		code.put("Baking powder / Soda", "bpd159");
		code.put("Bread crumbs", "bcr160");
		code.put("Cake / Brownie mix", "cbm161");
		code.put("Cake icing / Decorations", "cid162");
		code.put("Chocolate chips / Cocoa", "ccc163");
		code.put("Flour", "fou164");
		code.put("Shortening", "stn165");
		code.put("Sugar", "sgr166");
		code.put("Sugar substitute", "ssb167");
		code.put("Candy / Gum", "cag168");
		code.put("Cookies", "coo169");
		code.put("Crackers", "cra170");
		code.put("Dried fruit", "drf171");
		code.put("Granola bars / Mix", "gbm172");
		code.put("Nuts / Seeds", "nns173");
		code.put("Oatmeal", "oml174");
		code.put("Popcorn", "poc175");
		code.put("Potato / Corn chips", "pcc176");
		code.put("Pretzels", "pzs178");
		code.put("Burger night", "bun177");
		code.put("Chili night", "chn179");
		code.put("Pizza night", "pzn180");
		code.put("Spaghetti night", "spn181");
		code.put("Taco nigh", "tac182");
		code.put("Take-out deli food", "tdf183");
		code.put("Baby food", "bab184");
		code.put("Diapers", "dia185");
		code.put("Formula", "for186");
		code.put("Lotion", "lot187");
		code.put("Baby wash", "bwa188");
		code.put("Wipes", "wip189");
		code.put("Cat food / Treats", "cft190");
		code.put("Cat litter", "cal191");
		code.put("Dog food / Treats", "cft192");
		code.put("Flea treatment", "ft193");
		code.put("Pet shampoo", "pes194");
		code.put("Antiperspirant / Deodorant", "apd195");
		code.put("Bath soap / Hand soap", "bhs196");
		code.put("Condoms / Other b.c.", "cob197");
		code.put("Cosmetics", "cos198");
		code.put("Cotton swabs / Balls", "csb199");
		code.put("Facial cleanser", "fac200");
		code.put("Facial tissue", "fat201");
		code.put("Feminine products", "fep202");
		code.put("Floss", "flo203");
		code.put("Hair gel / Spray", "hgs204");
		code.put("Lip balm", "lib205");
		code.put("Moisturizing lotion", "mol206");
		code.put("Mouthwash", "mow207");
		code.put("Razors / Shaving cream", "rsc208");
		code.put("Shampoo / Conditioner", "shc209");
		code.put("Sunblock", "sub210");
		code.put("Toilet paper", "top211");
		code.put("Toothpaste", "top212");
		code.put("Vitamins / Supplements", "vsu213");
		code.put("Allergy", "all214");
		code.put("Antibiotic", "anb215");
		code.put("Antidiarrheal", "adi216");
		code.put("Aspirin", "asp217");
		code.put("Antacid", "ant218");
		code.put("Band-aids / Medical", "bam219");
		code.put("Cold / Flu / Sinus", "cfs220");
		code.put("Pain reliever", "par221");
		code.put("Prescription pick-up", "ppu222");
		code.put("Aluminum foil", "alf223");
		code.put("Napkins", "map224");
		code.put("Non-stick spray", "nss225");
		code.put("Paper towels", "pat226");
		code.put("Plastic wrap", "plw227");
		code.put("Sandwich / Freezer bags", "sfb228");
		code.put("Wax paper", "wap229");
		code.put("Air freshener", "aif230");
		code.put("Bathroom cleaner", "bac231");
		code.put("Bleach / Detergent", "bld232");
		code.put("Dish / Dishwasher soap", "dds233");
		code.put("Garbage bags", "gab234");
		code.put("Glass cleaner", "gls235");
		code.put("Mop head / Vacuum bags", "mvb236");
		code.put("Sponges / Scrubbers", "sps237");
		code.put("CDRs / DVDRs", "cdd238");
		code.put("Notepad / Envelopes", "nen239");
		code.put("Printer paper", "ppr240");
		code.put("Glue / Tape", "glt241");
		code.put("Pens / Pencils", "ppc242");
		code.put("Postage stamps", "pos243");
		code.put("Automotive", "aum244");
		code.put("Batteries", "bat245");
		code.put("Charcoal / Propane", "chp246");
		code.put("Flowers / Greeting card", "fgc247");
		code.put("Insect repellent", "irp248");
		code.put("Light bulbs", "lbl249");
		code.put("Newspaper / Magazine", "nma250");
		code.put("Random impulse buy", "rib251");
		code.put("Arsenic", "ars252");
		code.put("Cigarettes", "cir253");
		code.put("Asbestos", "asb254");
		code.put("Hummus", "hum255");
		code.put("Radionuclides", "rad256");
		code.put("Vinyl chloride", "vic257");

	}
	public String get_code(String item){
		String item_code=code.get(item);
		if(item_code==null){
			Error_Display error_display_obj=new Error_Display();
			error_display_obj.display("item_code not found");
			error_display_obj.setVisible(true);
			return null;
		}
		else {
			return item_code;
		}
	}
}
